//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rail.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class down_trainEntities4 : DbContext
    {
        public down_trainEntities4()
            : base("name=down_trainEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<down_11005> down_11005 { get; set; }
        public virtual DbSet<down_11013> down_11013 { get; set; }
        public virtual DbSet<down_11021> down_11021 { get; set; }
        public virtual DbSet<down_11301> down_11301 { get; set; }
        public virtual DbSet<down_14806> down_14806 { get; set; }
        public virtual DbSet<down_16209> down_16209 { get; set; }
        public virtual DbSet<down_16331> down_16331 { get; set; }
        public virtual DbSet<down_16339> down_16339 { get; set; }
        public virtual DbSet<down_16505> down_16505 { get; set; }
        public virtual DbSet<down_16507> down_16507 { get; set; }
        public virtual DbSet<down_16531> down_16531 { get; set; }
        public virtual DbSet<down_16533> down_16533 { get; set; }
        public virtual DbSet<down_16588> down_16588 { get; set; }
        public virtual DbSet<down_16613> down_16613 { get; set; }
        public virtual DbSet<down_19568> down_19568 { get; set; }
        public virtual DbSet<down_22497> down_22497 { get; set; }
        public virtual DbSet<down_82654> down_82654 { get; set; }
    }
}
