//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public int Train_number { get; set; }
        public string Source_Code { get; set; }
        public string Destination_code { get; set; }
        public Nullable<System.TimeSpan> schdep { get; set; }
        public Nullable<System.TimeSpan> scharr { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Priority { get; set; }
    }
}
