//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station_Code
    {
        public string Station_Code1 { get; set; }
        public string Station_name { get; set; }
        public double longitude { get; set; }
        public double latitude { get; set; }
    }
}
