//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class track_info
    {
        public string From_stn { get; set; }
        public string To_stn { get; set; }
        public int Track_route { get; set; }
    }
}
