//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rail.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class trainEntities : DbContext
    {
        public trainEntities()
            : base("name=trainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<priority> priorities { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
        public virtual DbSet<Station_Code> Station_Code { get; set; }
        public virtual DbSet<track_priority> track_priority { get; set; }
        public virtual DbSet<track_info> track_info { get; set; }
    }
}
