//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class up_22498
    {
        public int Sr_no { get; set; }
        public string Station_code { get; set; }
        public Nullable<System.TimeSpan> Arrival { get; set; }
        public Nullable<System.TimeSpan> Departure { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<int> Day { get; set; }
    }
}
