//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rail.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class up_trainEntities2 : DbContext
    {
        public up_trainEntities2()
            : base("name=up_trainEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<up_11006> up_11006 { get; set; }
        public virtual DbSet<up_11022> up_11022 { get; set; }
        public virtual DbSet<up_11302> up_11302 { get; set; }
        public virtual DbSet<up_14805> up_14805 { get; set; }
        public virtual DbSet<up_16210> up_16210 { get; set; }
        public virtual DbSet<up_16332> up_16332 { get; set; }
        public virtual DbSet<up_16340> up_16340 { get; set; }
        public virtual DbSet<up_16506> up_16506 { get; set; }
        public virtual DbSet<up_16508> up_16508 { get; set; }
        public virtual DbSet<up_16532> up_16532 { get; set; }
        public virtual DbSet<up_16534> up_16534 { get; set; }
        public virtual DbSet<up_16587> up_16587 { get; set; }
        public virtual DbSet<up_16614> up_16614 { get; set; }
        public virtual DbSet<up_19567> up_19567 { get; set; }
        public virtual DbSet<up_22498> up_22498 { get; set; }
        public virtual DbSet<up_82653> up_82653 { get; set; }
    }
}
